package com.biblequiz.infrastructure.seed.bible;

import com.biblequiz.infrastructure.bible.BibleStructure;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Data-integrity guard for the bundled Bible text (RVV11, Bản Truyền Thống Hiệu Đính 2010) that
 * {@link BibleTextImporter} loads on prod — generated by {@code scripts/bible/rvv11_to_seed.py}.
 *
 * <p>RVV11 numbers verses its own way in a few chapters (merged "17-18" blocks, verses only in late
 * manuscripts left out, Hebrew numbering in a few Old Testament chapters). The script lists those
 * chapters in {@code DIFFERENCES.md}; every other chapter must match {@link BibleStructure} exactly,
 * so a bad regeneration can't ship missing, shifted or blank verses.
 */
class BibleSeedContentTest {

    private static final String DIR = "seed/bible/rvv11/";
    private static final Map<String, List<BibleTextImporter.VerseRow>> BOOKS = new LinkedHashMap<>();
    /** "Matthew 17" → verses RVV11 has in that chapter, for every chapter DIFFERENCES.md lists. */
    private static final Map<String, Set<Integer>> DIFFERENT_CHAPTERS = new HashMap<>();
    /** "- Matthew 17: canonical 1-27, RVV11 1-27, no [21]" / "- Jonah 2: canonical 1-10, RVV11 1-11, extra [11]". */
    private static final Pattern DIFFERENCE =
            Pattern.compile("^- (.+) (\\d+): canonical 1-(\\d+), RVV11 1-(\\d+)(?:, no \\[([\\d, ]+)])?");

    @BeforeAll
    static void load() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath*:" + DIR + "*.json");
        Arrays.sort(resources, Comparator.comparing(Resource::getFilename));
        for (Resource r : resources) {
            try (InputStream in = r.getInputStream()) {
                BOOKS.put(r.getFilename(), mapper.readValue(in, new TypeReference<>() {}));
            }
        }
        try (InputStream in = new ClassPathResource(DIR + "DIFFERENCES.md").getInputStream()) {
            for (String line : new String(in.readAllBytes(), StandardCharsets.UTF_8).split("\n")) {
                Matcher m = DIFFERENCE.matcher(line);
                if (!m.find()) continue;
                Set<Integer> verses = new TreeSet<>();
                for (int v = 1; v <= Integer.parseInt(m.group(4)); v++) verses.add(v);
                if (m.group(5) != null) {
                    for (String n : m.group(5).split(",")) verses.remove(Integer.parseInt(n.trim()));
                }
                DIFFERENT_CHAPTERS.put(m.group(1) + " " + m.group(2), verses);
            }
        }
    }

    private static String bookOf(String file) {
        return BibleStructure.getCanonicalBooks().get(Integer.parseInt(file.substring(0, 2)) - 1);
    }

    @Test
    void hasOneFilePerCanonicalBookInOrder() {
        List<String> canon = BibleStructure.getCanonicalBooks();
        List<String> expected = new ArrayList<>();
        for (int i = 0; i < canon.size(); i++) {
            expected.add(String.format("%02d-%s.json", i + 1, canon.get(i).replace(' ', '_')));
        }
        assertEquals(expected, new ArrayList<>(BOOKS.keySet()));
    }

    @Test
    void chaptersMatchTheCanonicalTable_exceptTheListedDifferences() {
        assertFalse(DIFFERENT_CHAPTERS.isEmpty(), "DIFFERENCES.md lists no chapter");
        for (Map.Entry<String, List<BibleTextImporter.VerseRow>> e : BOOKS.entrySet()) {
            String book = bookOf(e.getKey());
            Map<Integer, List<BibleTextImporter.VerseRow>> byChapter = new TreeMap<>();
            for (BibleTextImporter.VerseRow row : e.getValue()) {
                byChapter.computeIfAbsent(row.chapter(), c -> new ArrayList<>()).add(row);
            }
            assertEquals(BibleStructure.getMaxChapter(book), byChapter.size(), book + " chapter count");
            for (Map.Entry<Integer, List<BibleTextImporter.VerseRow>> ch : byChapter.entrySet()) {
                String where = book + " " + ch.getKey();
                Set<Integer> covered = new TreeSet<>();
                int previousLast = 0;
                for (BibleTextImporter.VerseRow row : ch.getValue()) {
                    assertTrue(row.verse() > previousLast, where + ":" + row.verse() + " out of order or overlapping");
                    assertTrue(row.lastVerse() >= row.verse(), where + ":" + row.verse() + " bad verseEnd");
                    for (int v = row.verse(); v <= row.lastVerse(); v++) covered.add(v);
                    previousLast = row.lastVerse();
                }
                int count = BibleStructure.getVerseCount(book, ch.getKey());
                Set<Integer> canonical = new TreeSet<>();
                for (int v = 1; v <= count; v++) canonical.add(v);
                // A chapter DIFFERENCES.md lists must hold exactly what it says; every other one the canonical verses.
                assertEquals(DIFFERENT_CHAPTERS.getOrDefault(where, canonical), covered, where);
            }
        }
    }

    @Test
    void totalRows() {
        // 31,102 canonical verses, minus the verses RVV11 leaves out or merges, ± the Hebrew-numbering shifts.
        assertEquals(31_086, BOOKS.values().stream().mapToInt(List::size).sum());
    }

    @Test
    void textIsCleanNfcWithoutMarkup() {
        for (Map.Entry<String, List<BibleTextImporter.VerseRow>> e : BOOKS.entrySet()) {
            for (BibleTextImporter.VerseRow row : e.getValue()) {
                String where = e.getKey() + " " + row.chapter() + ":" + row.verse();
                assertFalse(row.text().isBlank(), where);
                assertFalse(row.text().matches(".*[<>{}\\\\⚓].*"), where + " has markup left");
                assertEquals(row.text().strip(), row.text(), where + " has surrounding whitespace");
                assertTrue(java.text.Normalizer.isNormalized(row.text(), java.text.Normalizer.Form.NFC), where);
            }
        }
    }

    @Test
    void spotCheckWellKnownVerses() {
        assertEquals("Vì Đức Chúa Trời yêu thương thế gian đến nỗi đã ban Con Một của Ngài, hầu cho hễ ai tin Con ấy "
                + "không bị hư mất mà được sự sống đời đời.", text("43-John.json", 3, 16));
        assertEquals("Ban đầu, Đức Chúa Trời sáng tạo trời và đất.", text("01-Genesis.json", 1, 1));
        assertEquals("Đức Giê-hô-va là Đấng chăn giữ tôi, Tôi sẽ chẳng thiếu thốn gì.", text("19-Psalms.json", 23, 1));
        // A merged block is stored once, under its first verse.
        BibleTextImporter.VerseRow block = row("05-Deuteronomy.json", 13, 17);
        assertEquals(18, block.verseEnd());
        assertTrue(BOOKS.get("05-Deuteronomy.json").stream().noneMatch(r -> r.chapter() == 13 && r.verse() == 18));
        // RVV11 leaves Matthew 17:21 out (footnote only).
        assertTrue(BOOKS.get("40-Matthew.json").stream().noneMatch(r -> r.chapter() == 17 && r.verse() == 21));
    }

    private static BibleTextImporter.VerseRow row(String file, int chapter, int verse) {
        return BOOKS.get(file).stream()
                .filter(r -> r.chapter() == chapter && r.verse() == verse)
                .findFirst().orElseThrow();
    }

    private static String text(String file, int chapter, int verse) {
        return row(file, chapter, verse).text();
    }
}
