/**
 * Custom Playwright fixtures — authenticated page contexts.
 *
 * Provides tier1Page through tier6Page (pre-authenticated via storageState)
 * and adminPage for admin-panel tests. Also exposes a testApi fixture.
 *
 * storageState files are generated by global-setup.ts.
 */

import { test as base, type Page } from '@playwright/test'
import { TestApi } from '../helpers/test-api'
import path from 'path'
import { fileURLToPath } from 'url'

// Resolve storage-state directory relative to this file
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const STORAGE_DIR = path.join(__dirname, 'storage-states')

type AuthFixtures = {
  tier1Page: Page
  tier2Page: Page
  tier3Page: Page
  tier4Page: Page
  tier5Page: Page
  tier6Page: Page
  adminPage: Page
  testApi: TestApi
}

// Login helper: returns Bearer token for API requests
const API_BASE =
  process.env.PLAYWRIGHT_API_URL ??
  ((process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:5173') === 'http://localhost:5173'
    ? 'http://localhost:8080'
    : (process.env.PLAYWRIGHT_BASE_URL as string))

async function getBearerToken(email: string): Promise<string> {
  const res = await fetch(`${API_BASE}/api/auth/mobile/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password: 'Test@123456' }),
  })
  const body = (await res.json()) as { accessToken: string }
  return body.accessToken
}

async function makeTierContext(browser: any, tier: number) {
  const token = await getBearerToken(`test${tier}@dev.local`)
  return browser.newContext({
    storageState: path.join(STORAGE_DIR, `tier${tier}.json`),
    extraHTTPHeaders: { Authorization: `Bearer ${token}` },
  })
}

export const test = base.extend<AuthFixtures>({
  tier1Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 1)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier2Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 2)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier3Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 3)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier4Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 4)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier5Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 5)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier6Page: async ({ browser }, use) => {
    const ctx = await makeTierContext(browser, 6)
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  adminPage: async ({ browser }, use) => {
    // Get admin access token once so page.request.* calls authenticate correctly
    // (storageState only has refresh_token cookie; Bearer header required for /api/admin/**)
    const loginRes = await fetch(`${API_BASE}/api/auth/mobile/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: 'admin@biblequiz.test', password: 'Test@123456' }),
    })
    const { accessToken } = (await loginRes.json()) as { accessToken: string }

    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'admin.json'),
      extraHTTPHeaders: { Authorization: `Bearer ${accessToken}` },
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  testApi: async ({}, use) => {
    const api = new TestApi()
    await api.init()
    await use(api)
  },
})

export { expect } from '@playwright/test'
